# Generated by Django 3.1.7 on 2021-04-12 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20210412_0305'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('pk_id', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=15, null=True)),
                ('type_1', models.CharField(max_length=15)),
                ('type_2', models.CharField(max_length=15, null=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.run')),
            ],
        ),
    ]
